// This file was auto-generated by ML.NET Model Builder. 

using System;
using İkinciML.Model;

namespace İkinciML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Req = 0F,
                Paket = 0F,
                Akan_byte = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Bool with predicted Bool from sample data...\n\n");
            Console.WriteLine($"Req: {sampleData.Req}");
            Console.WriteLine($"Paket: {sampleData.Paket}");
            Console.WriteLine($"Akan_byte: {sampleData.Akan_byte}");
            Console.WriteLine($"\n\nPredicted Bool value {predictionResult.Prediction} \nPredicted Bool scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
