// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace İkinciML.Model
{
    public class ModelInput
    {
        [ColumnName("req"), LoadColumn(0)]
        public float Req { get; set; }


        [ColumnName("paket"), LoadColumn(1)]
        public float Paket { get; set; }


        [ColumnName("akan byte"), LoadColumn(2)]
        public float Akan_byte { get; set; }


        [ColumnName("bool"), LoadColumn(3)]
        public string Bool { get; set; }


    }
}
